spring.application.name=e-Commerce-api

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.docker.compose.enabled=false

server.port=8080

jwt.secret=$UU8#jg*Q%Rq2#zWSDv4a!*dtJDVJ^3H4Rk0oUAmbe6g48$e92
jwt.expiration-ms=3600000


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true