{
 "title": "Pods monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"} == 1)\r\n",
     "legendFormat": "{{Pods running}}"
    }
   ]
  },
  {
   "title": "Pods restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[15m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_start_time{pod=~\"auth-service-.*|api-service-.*\"}) / 3600",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory per pod / container",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"$namespace\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"auth-service|api-service\"}[5m])) by (job, method, status)",
     "legendFormat": "{{job}}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "CPU per pod / container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"$namespace\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests per second per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (\r\n  rate(http_server_requests_seconds_count{\r\n    job=~\"api-service|auth-service\",\r\n    uri!~\"/actuator.*\",\r\n    uri!=\"UNKNOWN\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Auth success / error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (\r\n  rate(http_server_requests_seconds_count{\r\n    job=\"auth-service\",\r\n    uri=~\"/auth.*\",\r\n    uri!=\"UNKNOWN\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}