FROM mysql:8.0

# Setări de bază – le vei folosi și în Spring
ENV MYSQL_ROOT_PASSWORD=rootpass
ENV MYSQL_DATABASE=ecommerce
ENV MYSQL_USER=ecommerce_user
ENV MYSQL_PASSWORD=ecommerce_pass

# Portul standard MySQL
EXPOSE 3306
