{{- if and .Values.mysql .Values.mysql.enabled .Values.mysql.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: {{ .Values.mysql.secret.type | default "Opaque" }}
stringData:
{{- toYaml .Values.mysql.secret.stringData | nindent 2 }}
{{- end }}
